# Generated by Django 2.2 on 2020-08-14 05:02

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200811_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='task',
            name='descriptions',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[webapp.validators.cennz], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=100, validators=[webapp.validators.is_digit], verbose_name='Заголовок'),
        ),
    ]
