# Generated by Django 2.2 on 2020-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200814_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_data', models.DateField(verbose_name='Время начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончание')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('descriptions', models.TextField(max_length=3000, verbose_name='Описание')),
            ],
        ),
    ]
