# Generated by Django 2.2 on 2020-09-08 08:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0007_project_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(default=1, related_name='project', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
